on: [push, pull_request]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - run: sbt -v -Dfile.encoding=UTF-8 +test scalafmtCheckAll
      env:
        DATASTORE_PROJECT_ID: store4s
